# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# config for logging
# verbose_data: will print info in labeling_agent.py during data loading
# verbose_prompt: will print info for the input prompts used in every agent
# verbose_result: will print info for results returned by LLM/VLM agents
# verbose_speed: will print info for speed of running the LLM/VLM agents
verbose:
  verbose_prompt: true
  verbose_result: true
  verbose_speed: true
  verbose_data: true
